Bookstore: Use Redux in React components.
Moses-chibuike/bookstore pull request #3
Opened 2023-04-05 18:10 UTC by Moses-chibuike

- Display list of books books from Redux store.
- Added functionalities for "Add New", "Remove" and "check status" button clicks
- Dispatch actions using useDispatch

2023-04-05 20:06 UTC, OLIPLICHE requested changes
Hi @Moses-chibuike, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Used Redux Store 👍 
- Linter is green (the last commit have a green check mark (✅)) 👏

## Required Changes ♻️

- [ ] I see on the ReadMe file that you added Future Features section, I would advise you to include 1-3 potential features under this section, to avoid invalidation of your project, do not leave the section empty. This is part of the general requirements.
- NB: This comment above is not inline because you did not make the Readme file visible in this PR

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 20:06 UTC, OLIPLICHE commented on src/redux/books/books.js
>    switch (action.type) {
- [ ] Hi, In trying to run your App to check if Adding and removing are working which is part of the review requirements, here are the problem I found:
-  
![Capture](https://user-images.githubusercontent.com/63972670/230189823-88d3d225-e570-40cc-9ad6-3af36eb03dac.PNG)

- [ ]  I would suggest you open this link from [StackOverflow](https://stackoverflow.com/questions/62259351/react-redux-error-default-parameters-should-be-last-default-param-last), It might help you to solve this problem

2023-04-06 07:53 UTC, KayLemba approved these changes
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @Moses-chibuike      , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] Professional README 💯
- [x] Your work is well documented 🥇 
- [x] React Redux components setup correctly 🥇  











 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]s

2023-04-06 08:02 UTC, Moses-chibuike commented on src/redux/books/books.js
>    switch (action.type) {
thank you for the insight @OLIPLICHE

2023-04-06 08:04 UTC, Moses-chibuike commented
thanks for the swift response @KayLemba 💯

2023-04-06 21:23 UTC, merged